version: '3.8'
services:
  db:
    image: mysql:8.0.30
    ports:
      - 53002:3306
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - db:/var/lib/mysql
  api:
    build:
      context: .
      dockerfile: src/api/DockerFile
    ports:
      - 8000:8000
    tty: true
    volumes:
      - ./src/api:/api
    depends_on:
      - db
volumes:
  db: