FROM python:3.8

RUN mkdir /api
RUN pip3 install --upgrade pip
RUN pip3 install poetry

WORKDIR /api

COPY src/api/pyproject.toml* .
COPY src/api/poetry.lock* .
RUN poetry install

ENTRYPOINT ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--reload"]